name: Build & upload to Firebase App Distribution

on:
  push:
    branches: [ develop ]
  pull_request:
    branches:
      - develop
  workflow_dispatch: # 수동 실행 옵션

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LOCAL_PROPERTIES_CONTENTS: ${{ secrets.LOCAL_PROPERTIES_CONTENTS }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode and save keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > presentation/keystore.jks

      - name: Create google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" > presentation/google-services.json

      - name: Create local.properties
        run: |
          echo "$LOCAL_PROPERTIES_CONTENTS" > local.properties
          echo "SIGNED_STORE_FILE=keystore.jks" >> local.properties

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: nabi-team
          file: presentation/build/outputs/apk/debug/app-debug.apk
